<?php
include("../database/db_conn.php");



function findActiveSingers(){



  $query = "SELECT ARTIST_INFORMATION.ARTIST_INFO_ID AS SINGER_ID , ARTIST_INFORMATION.ARTIST_NAME AS SINGER_NAME,
  ARTIST_INFORMATION.NATIONALITY AS NATIONALITY, ARTIST_INFORMATION.ADDED_DATE AS ADDED_DATE FROM
  ARTIST_INFORMATION ORDER BY ARTIST_INFORMATION.ADDED_DATE DESC";
  
  return $query;
   
  
}







?>