<?php
include("../database/db_conn.php");



function findTracksBetweenTwoDates(){



  $query = "SELECT MUSIC_INFORMATION.MUSIC_INFO_ID AS TRACK_ID, MUSIC_INFORMATION.MUSIC_TITLE AS MUSIC_TITLE, 
  MUSIC_INFORMATION.ALBUM AS ALBUM,MUSIC_INFORMATION.ADDED_DATE AS ADDED_DATE, 
  ARTIST_INFORMATION.ARTIST_NAME AS SINGER_NAME FROM MUSIC_INFORMATION 
  INNER JOIN ARTIST_INFORMATION ON MUSIC_INFORMATION.ARTIST_INFO_ID = ARTIST_INFORMATION.ARTIST_INFO_ID 
 ORDER BY ARTIST_INFORMATION.ARTIST_NAME ASC  ";
  
  return $query;
   
  
}







?>