--FIND ARTIST NUMBER
SELECT COUNT(ARTIST_INFO_ID) FROM ARTIST_INFORMATION;

--FIND TOTAL MUSIC

SELECT COUNT(MUSIC_INFO_ID) FROM MUSIC_INFORMATION;

--SHOW TRACKS

SELECT MUSIC_INFORMATION.MUSIC_INFO_ID AS TRACK_ID, MUSIC_INFORMATION.MUSIC_TITLE AS MUSIC_TITLE, 
MUSIC_INFORMATION.ALBUM AS ALBUM,MUSIC_INFORMATION.ADDED_DATE AS ADDED_DATE, 
ARTIST_INFORMATION.ARTIST_NAME AS ARTIST_NAME FROM MUSIC_INFORMATION 
INNER JOIN ARTIST_INFORMATION ON MUSIC_INFORMATION.ARTIST_INFO_ID = ARTIST_INFORMATION.ARTIST_INFO_ID 
WHERE MUSIC_INFORMATION.ADDED_DATE BETWEEN '2022-05-26 11:05:16' AND '2022-11-01 03:00:49' 
GROUP BY ARTIST_INFORMATION.ARTIST_NAME ORDER BY MUSIC_INFORMATION.ADDED_DATE DESC;